# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

#target 'KoRouter' do
#  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
#
#  # Pods for KoRouter
#
#  target 'KorouterAppTests' do
#    # Pods for testing
#  end
#
#end

target 'KorouterApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KorouterApp
  pod 'KoRouter', :git => 'https://github.com/yashims/KoRouter.git', :tag => 'v0.0.1-1.3.70-eap'

  target 'KorouterAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
